name: Compile Examples

on:
  - push
  - pull_request

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        board:
          - fqbn: "teensy:avr:teensy40"
          - fqbn: "teensy:avr:teensy35"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile Examples
        uses: arduino/compile-sketches@main
        with:
          platforms: |
            - name: "teensy:avr"
              source-url: https://www.pjrc.com/teensy/td_156/package_teensy_index.json
            - name: "arduino:avr"
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - source-path: ./
